name: Deploy existing image from ACR to Azure Container Apps

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'ACR image tag to deploy'
        required: true
        default: 'latest'

permissions:
  id-token: write
  contents: read

env:
  RG: az-jrc-test
  ACA_APP: aztcsdavikk-2
  ACR_LOGIN_SERVER: acrtestfortcs-auc8eaa4eea7a2dn.azurecr.io   # <-- copia EXACTO del portal
  IMAGE_REPO: demo/hello-world

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Azure login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZTCSDAVIKK2_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZTCSDAVIKK2_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZTCSDAVIKK2_AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to Azure Container Apps
        uses: azure/container-apps-deploy-action@v2
        with:
          resourceGroup: ${{ env.RG }}
          containerAppName: ${{ env.ACA_APP }}
          imageToDeploy: ${{ env.ACR_LOGIN_SERVER }}/${{ env.IMAGE_REPO }}:${{ inputs.image_tag }}
          registryUrl: ${{ env.ACR_LOGIN_SERVER }}
          # No pongas registryIdentity aquí; ya debe estar configurado en el Container App
          # targetPort: 80
          # ingress: external

