name: Trigger auto deployment for aztcsdavikk-2

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/aztcsdavikk-2-AutoDeployTrigger-fb3afeb5-8010-4fae-9946-9c17412b0dd1.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZTCSDAVIKK2_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZTCSDAVIKK2_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZTCSDAVIKK2_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: acrtestfortcs-auc8eaa4eea7a2dn.azurecr.io
          registryUsername: ${{ secrets.AZTCSDAVIKK2_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.AZTCSDAVIKK2_REGISTRY_PASSWORD }}
          containerAppName: aztcsdavikk-2
          resourceGroup: az-jrc-test
          imageToBuild: acrtestfortcs-auc8eaa4eea7a2dn.azurecr.io/aztcsdavikk-2:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


