name: ACR Remote Build & Deploy to Azure Container Apps

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  # ==== Ajusta estos valores a tu entorno ====
  RG: az-jrc-test                     # Resource Group donde vive el Container App
  ACA_APP: aztcsdavikk-2              # Nombre del Container App
  ACR_NAME: acrtestfortcs             # Nombre del ACR (sin .azurecr.io)
  ACR_LOGIN_SERVER: acrtestfortcs.azurecr.io   # Login server del ACR
  IMAGE_REPO: aztcsdavikk-2           # Repo dentro del ACR para tu imagen
  IMAGE_TAG: ${{ github.sha }}        # Tag de la imagen (commit SHA)
  DOCKERFILE_PATH: ./Dockerfile       # Ruta al Dockerfile (ajusta si no está en la raíz)
  CONTEXT_PATH: .                     # Contexto de build (directorio a enviar al build)
  # ===========================================

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZTCSDAVIKK2_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZTCSDAVIKK2_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZTCSDAVIKK2_AZURE_SUBSCRIPTION_ID }}

      # Build remoto en ACR (empuja la imagen directo al registro)
      - name: ACR Remote Build
        run: |
          IMAGE=${{ env.ACR_LOGIN_SERVER }}/${{ env.IMAGE_REPO }}:${{ env.IMAGE_TAG }}
          az acr build \
            -r ${{ env.ACR_NAME }} \
            -t "$IMAGE" \
            -f "${{ env.DOCKERFILE_PATH }}" \
            "${{ env.CONTEXT_PATH }}"

      # Despliegue a Azure Container Apps (usando identidad del sistema para leer del ACR)
      - name: Deploy to Azure Container Apps
        uses: azure/container-apps-deploy-action@v2
        with:
          resourceGroup: ${{ env.RG }}
          appName: ${{ env.ACA_APP }}
          imageToDeploy: ${{ env.ACR_LOGIN_SERVER }}/${{ env.IMAGE_REPO }}:${{ env.IMAGE_TAG }}
          registryUrl: ${{ env.ACR_LOGIN_SERVER }}
          registryIdentity: system
          # Descomenta y ajusta si tu contenedor expone un puerto diferente:
          # targetPort: 80
          # ingress: external



