name: Deploy Nginx from ACR to Azure Container Apps

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'ACR image tag to deploy'
        required: true
        default: '1.27-alpine'   # tag que importaste al ACR

permissions:
  id-token: write
  contents: read

env:
  RG: az-jrc-test
  ACA_APP: aztcsdavikk-2
  ACR_LOGIN_SERVER: acrtestfortcs-auc8eaa4eea7a2dn.azurecr.io   # login server EXACTO
  IMAGE_REPO: demo/nginx                                        # repo en tu ACR

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Azure login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZTCSDAVIKK2_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZTCSDAVIKK2_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZTCSDAVIKK2_AZURE_SUBSCRIPTION_ID }}

      # Enlaza el ACR al Container App usando la identidad del sistema (idempotente)
      - name: Link ACR to Container App
        run: |
          az containerapp registry set \
            -g ${{ env.RG }} -n ${{ env.ACA_APP }} \
            --server ${{ env.ACR_LOGIN_SERVER }} \
            --identity system

      # Despliegue de la imagen existente en ACR + configuración de ingress/puerto
      - name: Deploy to Azure Container Apps
        uses: azure/container-apps-deploy-action@v2
        with:
          resourceGroup: ${{ env.RG }}
          containerAppName: ${{ env.ACA_APP }}
          imageToDeploy: ${{ env.ACR_LOGIN_SERVER }}/${{ env.IMAGE_REPO }}:${{ inputs.image_tag }}
          registryUrl: ${{ env.ACR_LOGIN_SERVER }}
          ingress: external          # endpoint público
          targetPort: 80             # Nginx escucha en 80

      # (Opcional pero recomendado) evita cold start
      - name: Ensure min replicas = 1
        run: |
          az containerapp update \
            -g ${{ env.RG }} -n ${{ env.ACA_APP }} \
            --min-replicas 1

      # (Opcional) imprime el FQDN para probar rápido
      - name: Show app FQDN
        run: |
          FQDN=$(az containerapp show -g ${{ env.RG }} -n ${{ env.ACA_APP }} --query "properties.configuration.ingress.fqdn" -o tsv)
          echo "FQDN: https://$FQDN"



